# Generated by Django 3.0.3 on 2020-03-04 15:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(default=None, max_length=100)),
                ('product_description', models.TextField()),
                ('brand', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=None)),
                ('item_height', models.PositiveSmallIntegerField()),
                ('item_width', models.PositiveSmallIntegerField()),
                ('item_lenght', models.PositiveSmallIntegerField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('seller_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=None)),
                ('cart_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='accounts.Item')),
            ],
        ),
    ]
