# Generated by Django 3.0.3 on 2020-03-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_cart_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic_1',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_2',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_3',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_4',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_5',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_6',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_pic_7',
            field=models.ImageField(default=None, upload_to='item_pics'),
        ),
    ]
