# Generated by Django 3.0.3 on 2020-03-05 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200305_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_lenght',
            new_name='item_length',
        ),
    ]
